### ISSUE TITLE
1.3.0: sphinx errors and warnings

### ISSUE THREAD

**Issue by kloczek** [python-hyper/priority#143]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.2
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [100%] using-priority
WARNING: autodoc: failed to import class 'PriorityError' from module 'priority'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'priority' has no attribute 'PriorityError'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: PriorityError

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-priority.3 { installation using-priority api security/index license authors } done
build succeeded, 2 warnings.
```

**Comment by Kriechi** [comment]
@kloczek you keep opening these issues without any description of what you expect and how you ended up there.
And I keep telling you that this is mostly your problem of not using the right commands or not setting up your venv correctly.

The docs build just fine in our CI on GitHub Actions: https://github.com/python-hyper/priority/runs/2365173128?check_suite_focus=true#step:6:43 and in https://python-hyper.org/projects/priority/en/latest/api.html itself.

**Comment by kloczek** [comment]
If you will try to upgrade to sphinx 4.0.2 you will see the same output.
And just checked your CI and looks like that CI is not not trying to build documentation.

**Comment by Kriechi** [comment]
I just built with Sphinx 4.0.2 locally (after bumping the dependency) and it works just fine. I will bump the dependency in the repo so you get to see the proof in our CI system.

It is building the docs - I provided the link to the output above.
