### ISSUE TITLE
priority doesn’t police the `maximum_streams` parameter

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/priority#56]
This is silly:

```pycon
>>> p = priority.PriorityTree(maximum_streams=-5)
>>> p.insert_stream(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chana/.virtualenvs/tempenv-577e1050112c7/lib/python3.6/site-packages/priority/priority.py", line 343, in insert_stream
    self._maximum_streams + 1
priority.priority.TooManyStreamsError: Refusing to insert -4 streams into priority tree at once
```

and this is confusing:

```pycon
>>> p = priority.PriorityTree(maximum_streams='foo')
>>> p.insert_stream(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chana/.virtualenvs/tempenv-577e1050112c7/lib/python3.6/site-packages/priority/priority.py", line 340, in insert_stream
    if (len(self._streams) + 1) > self._maximum_streams:
TypeError: '>' not supported between instances of 'int' and 'str'
```

Would be better if there was a little bit of checking that we’re not trying to create an obviously nonsensical tree.

**Comment by SethMichaelLarson** [comment]
Garbage in, garbage out. ;) Regardless, I think this would benefit from a type and positivity check. :)

**Comment by Lukasa** [comment]
Agreed. 😁
